version: "3"
name: time-tracker
services:
  time-tracker-db:
    image: docker.io/postgres:16-alpine
    networks:
      - apps
    ports:
      - "5432:5432"
    volumes:
      - prod_db-data:/var/lib/postgresql/data
      - ./backup:/backup:z
    env_file:
      - $PWD/../../time-tracker-db.env
    deploy:
      resources:
        limits:
          memory: 64M

  time-tracker-api:
    image: local/time-tracker-api
    build: ../../time-tracker-api
    networks:
      - apps
    depends_on:
      - time-tracker-db
    env_file:
      - $PWD/../../time-tracker-api.env
    deploy:
      resources:
        limits:
          memory: 384M
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3

  time-tracker-web:
    image: local/time-tracker-web
    build: ../../time-tracker-web
    networks:
      - apps
    deploy:
      resources:
        limits:
          memory: 32M

  time-tracker-reverse-proxy:
    image: nginx:1.15-alpine
    depends_on:
      - time-tracker-api
    networks:
      - apps
    expose:
      - 80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro,z
    deploy:
      resources:
        limits:
          memory: 64M
    healthcheck:
      test: curl -sS http://authorization-service:8080/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 5

volumes:
  prod_db-data:
    external: true

networks:
  apps:
    external: true
